[package]
name = "lapce-plugin-nushell-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
lapce-plugin = "0.1.2"
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
